// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BuyFuture.EfModels
{
    public partial class ImmediatePrice
    {
        public int StockNum { get; set; }
        public string StockName { get; set; }
        public string Price { get; set; }
    }
}