// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BuyFuture.EfModels
{
    public partial class Model
    {
        public Model()
        {
            UserModel = new HashSet<UserModel>();
        }

        public int Id { get; set; }
        public string ModelName { get; set; }

        public virtual ICollection<UserModel> UserModel { get; set; }
    }
}