// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BuyFuture.EfModels
{
    public partial class Price
    {
        public int Id { get; set; }
        public string StockNo { get; set; }
        public DateTime? Time { get; set; }
        public decimal? Price1 { get; set; }
        public decimal? Buy { get; set; }
        public decimal? Sell { get; set; }
        public decimal? UpDown { get; set; }
        public decimal? Volume { get; set; }
        public decimal? Close { get; set; }
        public decimal? Open { get; set; }
        public decimal? High { get; set; }
        public decimal? Low { get; set; }
    }
}