// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BuyFuture.EfModels
{
    public partial class Stock
    {
        public Stock()
        {
            UserStock = new HashSet<UserStock>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }

        public virtual ICollection<UserStock> UserStock { get; set; }
    }
}