// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BuyFuture.EfModels
{
    public partial class StockBasic
    {
        public StockBasic()
        {
            StockPrice = new HashSet<StockPrice>();
            TodayPrice = new HashSet<TodayPrice>();
            UserStock = new HashSet<UserStock>();
        }

        public int StockNum { get; set; }
        public string StockName { get; set; }

        public virtual ICollection<StockPrice> StockPrice { get; set; }
        public virtual ICollection<TodayPrice> TodayPrice { get; set; }
        public virtual ICollection<UserStock> UserStock { get; set; }
    }
}