// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BuyFuture.EfModels
{
    public partial class StockPrice
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public string AdjClose { get; set; }
        public string Close { get; set; }
        public string High { get; set; }
        public string Low { get; set; }
        public string Open { get; set; }
        public string Volume { get; set; }
        public int? StockNum { get; set; }

        public virtual StockBasic StockNumNavigation { get; set; }
    }
}