// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BuyFuture.EfModels
{
    public partial class TodayPrice
    {
        public int Id { get; set; }
        public DateTime? Time { get; set; }
        public int? StockNum { get; set; }
        public string Price { get; set; }
        public string Updown { get; set; }
        public string Vol { get; set; }
        public string High { get; set; }
        public string Low { get; set; }
        public string Open { get; set; }
        public string UpStop { get; set; }
        public string DownStop { get; set; }
        public string YClose { get; set; }

        public virtual StockBasic StockNumNavigation { get; set; }
    }
}